apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricradio-schema-registry-deployment
  labels:
    app: cricradio-schema-registry-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricradio-schema-registry
  
  template:
    metadata:
      labels:
        app: cricradio-schema-registry
    spec:
      containers:
      - name: cricradio-schema-registry
        image: confluentinc/cp-schema-registry:4.1.1
        ports:
        - containerPort: 38081
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: cricradio-zookeeper-service:32181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cricradio-schema-registry-svc
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://localhost:38081
        - name: SCHEMA_REGISTRY_DEBUG
          value: "true"
        - name: SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS
          value: GET,POST,PUT,OPTIONS
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: NET_RAW
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
