apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricradio-go
  labels:
    app: cricradio-go-deployment 


spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricradio-go
  
  template:
    metadata:
      name: cricradio-go-pod
      labels:
        app: cricradio-go
    spec:
      containers:
      - name: cricradio-go
        image: suhasgumma/cricradio-go-svc:kubernetesv2
        securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
                type: RuntimeDefault
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
                drop: NET_RAW
      securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 9900
