apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricradio-web-app-deployment
  labels:
    app: web-app-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  
  template:
    metadata:
      labels:
        app: web-app
    
    spec:
      containers:
      - name: cricradio-web-svc
        image: suhasgumma/cricradio-web-svc:kubernetesv2
        ports:
        - containerPort: 3000
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: NET_RAW
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
