apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricradio-kafka-rest
  labels:
    app: cricradio-kafka-rest-deployment


spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricradio-kafka-rest
  template:
    metadata:
      name: cricradio-kafka-rest-pod
      labels:
        app: cricradio-kafka-rest
    spec:
      containers:
      - name: cricradio-kafka-rest
        image: confluentinc/cp-kafka-rest:4.1.1
        ports:
        - containerPort: 38082
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: cricradio-zookeeper-service:32181
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: cricradio-schema-registry-svc:38081
        - name: KAFKA_REST_HOST_NAME
          value: cricradio-kafka-service
        - name: KAFKA_REST_LISTENERS
          value: http://localhost:38082
        - name: KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN
          value: "*"
        - name: KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS
          value: "GET,POST,PUT,DELETE"
        - name: KAFKA_REST_ACCESS_CONTROL_ALLOW_HEADERS
          value: "*"
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: NET_RAW
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
