apiVersion: v1
kind: Pod
metadata:
  name: insert_to_mapping_node_3
spec:
  containers:
  - name: nginx_container
    image: nginx
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: NET_RAW
      seccompProfile:
        type: RuntimeDefault
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false